### ISSUE TITLE
lc_line does not delete lines if number of elements is reduced on update

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/rlc#16]
If the values passed to x and y get reduced in length (for x) and number of columns (for y) in an update of the chart, the number of lines stays constant, and the now superfluous lines become static instead of getting deleted.

**Comment by kloivenn** [comment]
That's been a while since you've submitted this issue, but do you, by any chance, have an example? I've tried this and it works for me
```R
library(rlc)

x <- 1:10
y <- x %*% t(seq(-1, 1, length.out = 6))

lc_line(dat(x = x, y = y))

x <- 1:9
y <- x %*% t(seq(-1, 1, length.out = 4))

updateCharts()
```

**Comment by simon-anders** [comment]
Yes, I guess, that's what I meant. Seems you've fixed it in the meantime.
