### ISSUE TITLE
include example of R-base plot() or ggplot linkage with rlc

### ISSUE THREAD

**Issue by daaaaande** [anders-biostat/rlc#21]
AFAIK rlc is able to not only use the included plots (lc_scatter, lc_beeswarm) but also plots made with ggplot or base R plot functions. 
But i could not find it anywhere in the docs or tutorials.
Could you include a minimalistic example of how that would work?

**Comment by simon-anders** [comment]
Sorry, but that's not yet implemented.

The idea is that you could send static plots to the web page to appear at a specified place. Perhaps something like: 

```
lc_sendgg( ggplot(...)+geom_point(...), place="B2" )
```

to produce a standard ggplot and send it as PNG or SVG to the page. Of course, such a plot would be non-interactive as LinkeCharts cannot identify the individual items in the plot. But you might have an interactive master plot and a static detail plot, and there, this might be useful.

Problem is, we haven't implemented this yet. But it's on our to do list.

**Comment by kloivenn** [comment]
I've added lc_image function that can add static plots or locally stored images (ef5e16e).
```R
lc_image(src = "~/Pictures/Selection_005.png")
lc_image(img = ggplot() + geom_point(aes(1:10, 1:10)))
```
It requires the latest version of `jrc` (anders-biostat/jrc@3fdad67) and currently will not work on Windows. I'll close this issue as soon as I'll make it work for Windows as well.

Unfortunately, I don't know if it's possible to pass base R plots the same way as `ggplot` objects, so now the only way to include a base R plot is to first save is as an image and then give a path to this image to `lc_image`

**Comment by kloivenn** [comment]
Now it works also for Windows (b5bbd5e), but update to the latest version of `jrc` is required (
anders-biostat/jrc@68bec3d) 
`lc_image` can display images from any directory, but the server needs to get permission to access anything outside of current working directory or the server root directory. So, to open images from some custom directory one should specify the `allowedDirectories` argument of the `openPage` function:
```R
openPage(F, allowedDirectories = "~/Pictures")
lc_image(src = "~/Pictures/Selection_005.png")
```
I'm going to submit it to CRAN as `jrc v.0.4.0` within the next couple of days. New version of `rlc` will also be submitted to CRAN after I'll fix another issue.
