### ISSUE TITLE
all event handle properties should start with "on_"

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/rlc#3]
i.e., "on_markedUpdated" rather than "markedUpdated", to be consistant with "on_click". Also, perhaps, simply, "on_marked"

**Comment by kloivenn** [comment]
The following naming changes have been made (both in R and JavaScript versions):
- elementMouseOver -> on_mouseover
- elementMouseOut -> on_mouseout
- markedUpdated -> on_marked
- labelMouseOver -> on_mouseoverLabel
- labelMouseOut -> on_mouseoutLabel
