### ISSUE TITLE
lc_html should be reactive

### ISSUE THREAD

**Issue by simon-anders** [anders-biostat/rlc#4]
How about we make lc_html work like the chart functions? It gets a `dat` parameter that takes a property, `content` (or the like), and whenever `updateChart` is called, it sends the content to the brower to be put into the HTML tag indicated by `place`.

**Comment by kloivenn** [comment]
`lc_html` is now a chart with main property `content` and some other global chart's properties such as `width`, `height`, `title`, etc. There is also an `sendHTML` function in `JsRCom` package.
